<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Poe2StashPricer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Layouts.json" LogicalName="Poe2StashPricer.Layouts.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
