<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Version>0.1.1</Version>
    <Product>PoE2 Stash Pricer</Product>
    <Authors>gosferano</Authors>
    <Copyright>Copyright (c) 2026 tugayilik, Copyright (c) 2026 gosferano</Copyright>
    <RepositoryUrl>https://github.com/gosferano/poe2-stash-pricer</RepositoryUrl>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
